#server:
#  port: 8001
#
#spring:
#  application:
#    name: blog-user
#
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://${IP}:3306/blog-cloud?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
#    username: ${USERNAME}
#    password: ${PASSWORD}
#    hikari:
#      connection-timeout: 60000
#      validation-timeout: 3000
#      idle-timeout: 60000
#      login-timeout: 5
#      max-lifetime: 60000
#      maximum-pool-size: 10
#      minimum-idle: 10
#      read-only: false
#
#  cloud:
#    nacos:
#      discovery:
#        server-addr: ${NACOS_SERVER_ADDR}
#        namespace: c912c555-64d9-43c7-84ab-4b50818c0ffa
#
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath*:**/mapper/xml/*.xml
